### ISSUE TITLE
enhance.equalization.equalize_clahe() currently not differentiable

### ISSUE THREAD

**Issue by 8ToThePowerOfMol** [kornia/kornia#1355]
### Describe the bug

Whenever `equalize_clahe()` is used inside a backward pass, it previously performed non-differetiable operations such as `//` (floor division, C-like division) in the forward pass, while computing luts.

In `_compute_luts()` definition, there is default option `diff=False`, which I tried to set `True` inside `equalize_clahe()`. This fixes subsequent histogram calculation differentiability, but the main bug still remains:
```python
kornia/enhance/equalization.py:353:    luts: torch.Tensor = _compute_luts(hist_tiles, clip=clip_limit, diff=True)  # B x GH x GW x C x B
```

### Reproduction steps

```python
import torch
from kornia.enhance.equalization import equalize_clahe

with torch.autograd.detect_anomaly():
    img = torch.rand((2, 3, 10, 20), requires_grad=True)
    res = equalize_clahe(img)
    res.sum().backward()
    print(img.grad, img.grad.sum())
```
currently outputs:
```
clahe_bug.py:4: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
  with torch.autograd.detect_anomaly():
/mnt/home.stud/mohwaalb/env_torch1.7.0/lib/python3.7/site-packages/torch/autograd/__init__.py:132: UserWarning: Error detected in torch::autograd::NotImplemented. Traceback of forward call that caused the error:
  File "clahe_bug.py", line 6, in <module>
    res = equalize_clahe(img)
  File "/mnt/home.stud/mohwaalb/mdir_extra/mdir/external/kornia/utils/image.py", line 179, in _wrapper
    output: torch.Tensor = f(input, *args, **kwargs)
  File "/mnt/home.stud/mohwaalb/mdir_extra/mdir/external/kornia/enhance/equalization.py", line 353, in equalize_clahe
    luts: torch.Tensor = _compute_luts(hist_tiles, clip=clip_limit, diff=False)  # B x GH x GW x C x B
  File "/mnt/home.stud/mohwaalb/mdir_extra/mdir/external/kornia/enhance/equalization.py", line 152, in _compute_luts
    redist: torch.Tensor = clipped // num_bins
  File "/mnt/home.stud/mohwaalb/env_torch1.7.0/lib/python3.7/site-packages/torch/tensor.py", line 27, in wrapped
    return f(*args, **kwargs)
  File "/mnt/home.stud/mohwaalb/env_torch1.7.0/lib/python3.7/site-packages/torch/tensor.py", line 551, in __floordiv__
    return torch.floor_divide(self, other)
 (Triggered internally at  /pytorch/torch/csrc/autograd/python_anomaly_mode.cpp:104.)
  allow_unreachable=True)  # allow_unreachable flag
Traceback (most recent call last):
  File "clahe_bug.py", line 7, in <module>
    res.sum().backward()
  File "/mnt/home.stud/mohwaalb/env_torch1.7.0/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/mnt/home.stud/mohwaalb/env_torch1.7.0/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: derivative for floor_divide is not implemented
```

### Expected behavior

To pass without an exception and to print varying non-zero gradients of the CLAHEed tensor.

### Environment

```shell
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 9.3 (stretch) (x86_64)
GCC version: (GCC) 8.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.2.5

Python version: 3.7.2 (default, May 23 2019, 17:57:10)  [GCC 8.2.0] (64-bit runtime)
Python platform: Linux-4.9.0-4-amd64-x86_64-with-debian-9.3
Is CUDA available: True
CUDA runtime version: 10.1.105
GPU models and configuration:
GPU 0: NVIDIA GeForce GTX 1080 Ti

Nvidia driver version: 470.57.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.7.0
[pip3] torchaudio==0.7.0
[pip3] torchvision==0.8.0
[conda] Could not collect

kornia==0.5.11
```

**Comment by edgarriba** [comment]
@8ToThePowerOfMol thanks to report this. The issue seems to be here
https://github.com/kornia/kornia/blob/master/kornia/enhance/equalization.py#L152

/cc @lferraz is there any way to skip this ? Besides, we might abstract `compute_lut` outside from clahe

**Comment by ducha-aiki** [comment]
<img width="589" alt="image" src="https://user-images.githubusercontent.com/4803565/136186617-e1695729-ceaf-4149-8c98-c5ef9f3c0e88.png">
