### ISSUE TITLE
The RandomPosterize class raises RuntimeError because of conflicting devices.

### ISSUE THREAD

**Issue by RElbers** [kornia/kornia#1528]
### Describe the bug

Using the _RandomPosterize_ class on the GPU device raises the following exception:

```
  File "<...>\Python39\lib\site-packages\kornia\enhance\adjust.py", line 509, in _right_shift
    return (input * 255).to(torch.uint8) / (2 ** shift).to(input.dtype) / 255.0
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

It seems like it's caused by the _bits_ variable not being placed on the same device. It's probably fixed just by placing something like the below code in the _posterize_ function.

```
if bits.device != input.device:
    bits = bits.to(input.device)
```

### Reproduction steps

```bash
import torch
from kornia.augmentation import RandomPosterize
from kornia.enhance import posterize

# On CPU works
transform = RandomPosterize(bits=6, p=1.0)
input = torch.rand(size=(1, 3, 128, 128),  dtype=torch.float32)
out = transform(input)

# On GPU fails with: RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
transform = RandomPosterize(bits=6, p=1.0).to('cuda:0')
input = torch.rand(size=(1, 3, 128, 128), device='cuda:0', dtype=torch.float32)
out = transform(input)

# The posterize function fails, because bits and input are on different devices
input = torch.rand(size=(1, 3, 128, 128), device='cuda:0', dtype=torch.float32)
bits = torch.tensor([6], device='cpu', dtype=torch.int32)
out = posterize(input, bits)
```

### Expected behavior

The `RandomPosterize` class should work on all devices.

### Environment
Using Kornia 0.6.2

```shell
PyTorch version: 1.10.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: (x86_64-posix-seh, Built by strawberryperl.com project) 8.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: 11.5.119
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060
Nvidia driver version: 497.29
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] catatorch==0.1.0
[pip3] info-nce-pytorch==0.1.4
[pip3] numpy==1.20.2
[pip3] pytorch-lightning==1.5.7
[pip3] pytorch-lightning-bolts==0.3.2
[pip3] rmi-pytorch==0.1.1
[pip3] torch==1.10.1+cu113
[pip3] torchaudio==0.10.1+cu113
[pip3] torchinfo==1.5.3
[pip3] torchmetrics==0.6.1
[pip3] torchvision==0.11.2+cu113
[conda] Could not collect
```

**Comment by edgarriba** [comment]
Hi! Do you have the full log error?

**Comment by RElbers** [comment]
Full output for the reproduction script:

```
C:\Users\Robin\AppData\Local\Programs\Python\Python39\python.exe C:/Dev/projects/grass/grass-classification-project/src/posterize.py
Traceback (most recent call last):
  File "C:\Dev\projects\grass\grass-classification-project\src\posterize.py", line 13, in <module>
    out = transform(input)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python39\lib\site-packages\kornia\augmentation\base.py", line 270, in forward
    output = self.apply_func(in_tensor, in_transform, self._params, return_transform)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python39\lib\site-packages\kornia\augmentation\base.py", line 229, in apply_func
    output = self.apply_transform(in_tensor, params, trans_matrix)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python39\lib\site-packages\kornia\augmentation\augmentation.py", line 1543, in apply_transform
    return posterize(input, params["bits_factor"])
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python39\lib\site-packages\kornia\utils\image.py", line 227, in _wrapper
    output: torch.Tensor = f(input, *args, **kwargs)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python39\lib\site-packages\kornia\enhance\adjust.py", line 521, in posterize
    return _posterize_one(input, bits)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python39\lib\site-packages\kornia\enhance\adjust.py", line 518, in _posterize_one
    return _left_shift(_right_shift(input, bits), bits)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python39\lib\site-packages\kornia\enhance\adjust.py", line 509, in _right_shift
    return (input * 255).to(torch.uint8) / (2 ** shift).to(input.dtype) / 255.0
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Comment by edgarriba** [comment]
Awesome, I’ll fix during the weekend
