### ISSUE TITLE
Incorrect shape while using CombineTensorPatches

### ISSUE THREAD

**Issue by ashnair1** [kornia/kornia#1557]
### Describe the bug

Currently `CombineTensorPatches` does not accurately invert the results of `ExtractTensorPatches`. This can be observed by running the following script.

### Reproduction steps

```bash
import torch

from kornia.contrib import CombineTensorPatches, ExtractTensorPatches

# Original size
h, w = 16, 16
# Window size
win = 2

image = torch.randn(2, 3, h, w)
print(image.shape)
tiler = ExtractTensorPatches(window_size=win, stride=win, padding=0)
merger = CombineTensorPatches(window_size=win, unpadding=0)
image_tiles = tiler(image)
new_image = merger(image_tiles)
print(new_image.shape)
assert (image == new_image).all()
```

Instead of returning the original shape (2,3,16,16), `CombineTensorPatches` will return (32, 3, 4, 4)

### Expected behavior

image and new_image should have the same shape - (2,  3, 16, 16)

### Environment

```shell
I used the devcontainer


PyTorch version: 1.10.2+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.12 (default, Dec 21 2021, 10:45:09)  [GCC 10.2.1 20210110] (64-bit runtime)
Python platform: Linux-5.4.0-96-generic-x86_64-with-glibc2.2.5
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy==0.931
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.2
[pip3] pytest-mypy==0.8.1
[pip3] torch==1.10.2
[pip3] torchvision==0.11.3
[conda] Could not collect


```
### Additional context

This error is caused by `CombineTensorPatches` not taking into account the original size of the image. It can be solved by setting `window_size = (original_size[0] // window_size[0], original_size[1] // window_size[1])`. I've opened a PR to implement this fix.

**Comment by ashnair1** [comment]
The same bug can cause the script to fail earlier if you use a larger window size

```
import torch

from kornia.contrib import CombineTensorPatches, ExtractTensorPatches

# Original size
h, w = 5000, 5000
# Window size
win = 512

image = torch.randn(2, 3, h, w)
print(image.shape)
tiler = ExtractTensorPatches(window_size=win, stride=win, padding=0)
merger = CombineTensorPatches(window_size=win, unpadding=0)
image_tiles = tiler(image)
new_image = merger(image_tiles)
print(new_image.shape)
assert (image == new_image).all()
```

Error produced

```
Traceback (most recent call last):
  File "tile_combine.py", line 13, in <module>
    new_image = merger(image_tiles)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspaces/kornia/kornia/contrib/extract_patches.py", line 140, in forward
    return combine_tensor_patches(
  File "/workspaces/kornia/kornia/contrib/extract_patches.py", line 186, in combine_tensor_patches
    patches_tensor = patches.view(-1, window_size[0], window_size[1], *patches.shape[-3:])
RuntimeError: shape '[-1, 512, 512, 3, 512, 512]' is invalid for input of size 127401984
```

**Comment by ashnair1** [comment]
Looking into this further, I realize the first issue is mainly due to an issue with ExtractPatches.  Basically the window size used is incorrect. It should be input_size // win_size. This is why a similar augmentation like `PatchSequential` works. It correctly computes the window size before calling `extract_patches`. I can submit a PR but we need to decide if the window size computation should be done in `extract_patches`.
