### ISSUE TITLE
LoFTR(pretrained="outdoor"),AttributeError: module 'signal' has no attribute 'SIGKILL'

### ISSUE THREAD

**Issue by monkeycc** [kornia/kornia#2021]
### Describe the bug

```
NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "ko.py", line 1, in <module>
    from kornia.feature import LoFTR
  File "D:\anaconda31114\envs\biaozhu\lib\site-packages\kornia\__init__.py", line 8, in <module>
    from . import augmentation, color, contrib, core, enhance, feature, io, losses, metrics, morphology, tracking, utils, x
  File "D:\anaconda31114\envs\biaozhu\lib\site-packages\kornia\x\__init__.py", line 2, in <module>
    from .trainer import Trainer
  File "D:\anaconda31114\envs\biaozhu\lib\site-packages\kornia\x\trainer.py", line 11, in <module>
    from accelerate import Accelerator
  File "D:\anaconda31114\envs\biaozhu\lib\site-packages\accelerate\__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "D:\anaconda31114\envs\biaozhu\lib\site-packages\accelerate\accelerator.py", line 27, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "D:\anaconda31114\envs\biaozhu\lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "D:\anaconda31114\envs\biaozhu\lib\site-packages\accelerate\utils\__init__.py", line 96, in <module>
    from .launch import PrepareForLaunch, _filter_args, get_launch_prefix
  File "D:\anaconda31114\envs\biaozhu\lib\site-packages\accelerate\utils\launch.py", line 25, in <module>
    import torch.distributed.run as distrib_run
  File "D:\anaconda31114\envs\biaozhu\lib\site-packages\torch\distributed\run.py", line 386, in <module>
    from torch.distributed.launcher.api import LaunchConfig, elastic_launch
  File "D:\anaconda31114\envs\biaozhu\lib\site-packages\torch\distributed\launcher\__init__.py", line 10, in <module>
    from torch.distributed.launcher.api import (  # noqa: F401
  File "D:\anaconda31114\envs\biaozhu\lib\site-packages\torch\distributed\launcher\api.py", line 15, in <module>
    from torch.distributed.elastic.agent.server.api import WorkerSpec
  File "D:\anaconda31114\envs\biaozhu\lib\site-packages\torch\distributed\elastic\agent\server\__init__.py", line 40, in <module>
    from .local_elastic_agent import TORCHELASTIC_ENABLE_FILE_TIMER, TORCHELASTIC_TIMER_FILE
  File "D:\anaconda31114\envs\biaozhu\lib\site-packages\torch\distributed\elastic\agent\server\local_elastic_agent.py", line 19, in <module>
    import torch.distributed.elastic.timer as timer
  File "D:\anaconda31114\envs\biaozhu\lib\site-packages\torch\distributed\elastic\timer\__init__.py", line 44, in <module>
    from .file_based_local_timer import FileTimerClient, FileTimerServer, FileTimerRequest  # noqa: F401
  File "D:\anaconda31114\envs\biaozhu\lib\site-packages\torch\distributed\elastic\timer\file_based_local_timer.py", line 63, in <module>
    class FileTimerClient(TimerClient):
  File "D:\anaconda31114\envs\biaozhu\lib\site-packages\torch\distributed\elastic\timer\file_based_local_timer.py", line 81, in FileTimerClient
    def __init__(self, file_path: str, signal=signal.SIGKILL) -> None:
AttributeError: module 'signal' has no attribute 'SIGKILL'
```

### Reproduction steps

```bash
from kornia.feature import LoFTR
import cv2

img_raw = cv2.imread("F:/2022/9/1.bmp", cv2.IMREAD_COLOR)
img_raw2 = cv2.imread("F:/2022/9/2.bmp", cv2.IMREAD_COLOR)

matcher = LoFTR(pretrained="outdoor")
input = {"image0": img_raw, "image1": img_raw2}
correspondences_dict = matcher(input)
```
```


### Expected behavior

....

### Environment

```shell
Collecting environment information...
PyTorch version: 1.13.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.13 (default, Oct 19 2022, 22:38:03) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: False
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080 Ti Laptop GPU
Nvidia driver version: 516.40
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==1.13.0
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] torch                     1.13.0                   pypi_0    pypi
```

**Comment by edgarriba** [comment]
you might have to convert opencv numpy array to torch tensor via `kornia.utils.image_to_tensor`

an alternative is to use our own image loader `kornia.io.read_image`
https://kornia.readthedocs.io/en/latest/io.html

**Comment by monkeycc** [comment]
1.
```
img_raw = cv2.imread("F:/2022/PJ/9/1.bmp", cv2.IMREAD_COLOR)
img_raw2 = cv2.imread("F:/2022/PJ/9/2.bmp", cv2.IMREAD_COLOR)


img_raw3 = K.utils.image_to_tensor(img_raw)
img_raw4 = K.utils.image_to_tensor(img_raw2)


matcher = LoFTR(pretrained="outdoor")
input = {"image0": img_raw3, "image1": img_raw4}
correspondences_dict = matcher(input)
```
`AttributeError: module 'signal' has no attribute 'SIGKILL'
`

2.
kornia.io.read_image
For now we only support Linux platforms.
```
img: Tensor = K.io.load_image("F:/2022/PJ/9/1.bmp", ImageType.UNCHANGED, device="cuda")
img2: Tensor = K.io.load_image("F:/2022/PJ/9/2.bmp", ImageType.UNCHANGED, device="cuda")


matcher = LoFTR(pretrained="outdoor")
input = {"image0": img, "image1": img2}
correspondences_dict = matcher(input)
```
`AttributeError: module 'signal' has no attribute 'SIGKILL'
`

It's a pity they all failed

Is it because it is a win system
I'm going to try to do it with Linux

**Comment by monkeycc** [comment]
Linux test passed

It seems to be a problem with the win system


https://kornia.readthedocs.io/en/latest/io.html
I install RUST  in Win
But I still can't use it
Adjust profile?

**Comment by edgarriba** [comment]
in principle kornia_rs should work on windows too: https://github.com/kornia/kornia-rs/blob/main/.github/workflows/release.yml#L95  docs need to be updated 

https://github.com/facebookresearch/fairseq/issues/3187

**Comment by edgarriba** [comment]
If anyone is interested in this, feel free to re-open the ticket. Thanks!
