### ISSUE TITLE
Error in dlopen libtorch_cuda_linalg.so undefined symbol: culibosInit

### ISSUE THREAD

**Issue by elgalu** [kornia/kornia#2080]
### Describe the bug

Getting Error in dlopen libtorch_cuda_linalg.so undefined symbol: culibosInit when using `kornia.geometry.transform.crop_and_resize()` on PT 1.13.0. Works fine with PT 1.21.1

The error points to https://github.com/kornia/kornia/blob/ed8813a80c8bc96637411d301ec049325f18f14c/kornia/utils/helpers.py#L188 and is easy to reproduce.

### Reproduction steps

1. Pull AWS PT 1.13.0 cu117 image

```sh
docker run --rm -ti --gpus=0 "763104351884.dkr.ecr.eu-central-1.amazonaws.com/pytorch-training:1.13.0-gpu-py39-cu117-ubuntu20.04-ec2" bash
root@5e2b2957c410:/# pip install kornia==0.6.8
root@5e2b2957c410:/# python
```

2. Reproduce the error

```py
import torch
im_data = torch.ones([120, 3, 367, 254], dtype=torch.int32, device='cuda:0')
bounding_boxes = torch.ones([120, 4, 2], dtype=torch.int32, device='cuda:0')
output_size = (256, 177)

import kornia
kornia.geometry.transform.crop_and_resize(im_data, bounding_boxes, output_size)
```

```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.9/site-packages/kornia/geometry/transform/crop2d.py", line 83, in crop_and_resize
    return crop_by_boxes(tensor, points_src, points_dst, mode, padding_mode, align_corners)
  File "/opt/conda/lib/python3.9/site-packages/kornia/geometry/transform/crop2d.py", line 226, in crop_by_boxes
    dst_trans_src: torch.Tensor = get_perspective_transform(src_box.to(tensor), dst_box.to(tensor))
  File "/opt/conda/lib/python3.9/site-packages/kornia/geometry/transform/imgwarp.py", line 361, in get_perspective_transform
    X: Tensor = _torch_solve_cast(A, b)
  File "/opt/conda/lib/python3.9/site-packages/kornia/utils/helpers.py", line 167, in _torch_solve_cast
    out = torch.linalg.solve(A.to(dtype), B.to(dtype))
RuntimeError: Error in dlopen: /opt/conda/lib/python3.9/site-packages/torch/lib/libtorch_cuda_linalg.so: undefined symbol: culibosInit
```

### Expected behavior

Not to fail with `undefined symbol: culibosInit` but rather, in this case, throw the proper error `The diagonal element 1 is zero, the solve could not be completed because the input matrix is singular.` as in PT 1.12.1

### Environment

- PyTorch Version (e.g., 1.0): 1.13.0
- OS (e.g., Linux): Linux
- How you installed PyTorch (`conda`, `pip`, source): pip , see SageMaker build pipeline https://github.com/aws/deep-learning-containers/blob/5b93de6f55b89eba0c0119fab1eb479f6d2cc307/pytorch/training/docker/1.13/py3/cu117/Dockerfile.gpu#L249
- Build command you used (if compiling from source): no
- Python version: 3.9.13
- CUDA/cuDNN version: Driver Version: 515.65.01    CUDA Version: 11.7
- GPU models and configuration: Tesla V100-SXM2-16GB
- Any other relevant information: The container image can be pulled from AWS `763104351884.dkr.ecr.eu-central-1.amazonaws.com/pytorch-training:1.13.0-gpu-py39-cu117-ubuntu20.04-ec2`
- Kornia version: Same error happens with 0.5.10 up to latest, also master branch. On version 0.5.8 the error is `RuntimeError: This function was deprecated since version 1.9 and is now removed. Please use the `torch.linalg.solve` function instead.`.

```sh
PyTorch version: 1.13.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.3
Libc version: glibc-2.31

Python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-50-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB

Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.5.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] pytorch-lightning==1.8.4.post0
[pip3] torch==1.13.0+cu117
[pip3] torchaudio==0.13.0+cu117
[pip3] torchdata==0.5.0
[pip3] torchmetrics==0.11.0
[pip3] torchnet==0.0.4
[pip3] torchvision==0.14.0+cu117
[conda] magma-cuda117             2.6.1                         1    pytorch
[conda] mkl                       2022.1.0           h84fe81f_915    conda-forge
[conda] mkl-include               2022.1.0           h84fe81f_915    conda-forge
[conda] numpy                     1.23.4           py39h3d75532_1    conda-forge
[conda] pytorch-lightning         1.8.4.post0              pypi_0    pypi
[conda] torch                     1.13.0+cu117             pypi_0    pypi
[conda] torchaudio                0.13.0+cu117             pypi_0    pypi
[conda] torchdata                 0.5.0                    pypi_0    pypi
[conda] torchmetrics              0.11.0                   pypi_0    pypi
[conda] torchnet                  0.0.4                    pypi_0    pypi
[conda] torchvision               0.14.0+cu117             pypi_0    pypi
```

### Additional context

Works fine with Pytorch 1.12.1

**Comment by johnnv1** [comment]
It's a problem related to your docker image, this image does not have the shared object `libtorch_cuda_linalg.so` (or at least the torch cannot be found)

Your example is working fine with at torch 1.13

**Comment by elgalu** [comment]
Thanks João, I'll report this in https://github.com/aws/deep-learning-containers
