### ISSUE TITLE
force_seed_mnn bug in docs

### ISSUE THREAD

**Issue by Sprinter1999** [kornia/kornia#2161]
## 📚 Documentation
when running the example code of https://kornia-tutorials.readthedocs.io/en/latest/image_matching_adalam.html, an error raised:
```linux
Traceback (most recent call last):
  File "keynet_cv2.py", line 54, in <module>
    dists, idxs = KF.match_adalam(descs1.squeeze(0), descs2.squeeze(0),
  File "C:\Users\xuefengj\AppData\Local\Programs\Python\Python38\lib\site-packages\kornia\feature\adalam\adalam.py", line 72, in match_adalam
    idxs, quality = adalam_object.match_and_filter(
  File "C:\Users\xuefengj\AppData\Local\Programs\Python\Python38\lib\site-packages\kornia\feature\adalam\adalam.py", line 239, in match_and_filter
    if self.config['force_seed_mnn']:
KeyError: 'force_seed_mnn'
```
BTW, the version of running environment is updated to the latest version.

**Comment by edgarriba** [comment]
@ducha-aiki any idea about this ?

**Comment by ducha-aiki** [comment]
@Sprinter1999 thanks for the catch.

It seems that the problem is in https://github.com/kornia/kornia/pull/2092, which deleted the logic of only changing provided parts in the default AdaLAM config 
@johnnv1
