### ISSUE TITLE
Error when supplying `normalize_range` argument to `diamond_square`

### ISSUE THREAD

**Issue by hennels** [kornia/kornia#2281]
### Describe the bug

When the `normalize_range` argument is supplied to `kornia.contrib.diamond_square`, it always produces the error:
```python
>>> kornia.contrib.diamond_square((1, 1, 128, 128), normalize_range=(0., 1.))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\nehn0\AppData\Local\pypoetry\Cache\virtualenvs\surfaceclutter-aKm1AMFl-py3.8\lib\site-packages\kornia\contrib\diamond_square.py", line 210, in diamond_square
    img = normalize_min_max(img, min_val, max_val)
  File "C:\Users\nehn0\AppData\Local\pypoetry\Cache\virtualenvs\surfaceclutter-aKm1AMFl-py3.8\lib\site-packages\kornia\enhance\normalize.py", line 284, in normalize_min_max
    x_min: torch.Tensor = x.view(B, C, -1).min(-1)[0].view(B, C, 1)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

Additionally, the type annotation for the argument is incorrect. It is annotated as `Optional[Tuple[int, int]]` but when `int`s are supplied instead of `float`s the following error is produced:
```python
kornia.contrib.diamond_square((1, 1, 128, 128), normalize_range=(0, 1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\nehn0\AppData\Local\pypoetry\Cache\virtualenvs\surfaceclutter-aKm1AMFl-py3.8\lib\site-packages\kornia\contrib\diamond_square.py", line 210, in diamond_square
    img = normalize_min_max(img, min_val, max_val)
  File "C:\Users\nehn0\AppData\Local\pypoetry\Cache\virtualenvs\surfaceclutter-aKm1AMFl-py3.8\lib\site-packages\kornia\enhance\normalize.py", line 273, in normalize_min_max
    raise TypeError(f"'min_val' should be a float. Got: {type(min_val)}.")
TypeError: 'min_val' should be a float. Got: <class 'int'>.
```

### Reproduction steps

```bash
import kornia

# call with ints
kornia.contrib.diamond_square((1, 1, 128, 128), normalize_range=(0, 1))

# call with floats
kornia.contrib.diamond_square((1, 1, 128, 128), normalize_range=(0., 1.))
```

### Expected behavior

Using the `normalize_range` argument should not produce an error and should normalize the output array to be between the two supplied values.

### Environment

```shell
- PyTorch Version (e.g., 1.0): 1.13.1
- OS (e.g., Linux): Windows 10
- How you installed PyTorch (`conda`, `pip`, source): pip
- Build command you used (if compiling from source):
- Python version: 3.8.7
- CUDA/cuDNN version: None
- GPU models and configuration: None
- Any other relevant information: None
```

**Comment by edgarriba** [comment]
@hennels thanks! that's definitely a bug; the second it can be easily adjusted. Are you willing to send a PR with a fix ?

**Comment by hennels** [comment]
Yes, I have a fix and will make a PR.
