### ISSUE TITLE
Add/ensure python 3.11 support 

### ISSUE THREAD

**Issue by johnnv1** [kornia/kornia#2385]
## 🚀 Feature
Ensure support for py311 by adding it to the CI

## Motivation
The py311 version was released on 2022-10-24 and pytorch 1.13 and 2.0 supports it at least partially.

## Pitch
1. Update the [CI's](https://github.com/kornia/kornia/tree/master/.github) to run py311 for 2.0 and 1.13
1. Update the `torch_optimizer` to skip if is py311 on [conftest.py](https://github.com/kornia/kornia/blob/master/conftest.py) -- compile API is not yet fully supported
1. Fixes the falling tests that appear

____________________________________________________________________

#### Consider also contributing to Kornia universe projects :)

<sub>

- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.

</sub>

**Comment by crazyfish2020** [comment]
Textual inversion embeddings loaded(0): 
Model loaded in 8.3s (load weights from disk: 0.3s, create model: 0.8s, apply weights to model: 5.1s, move model to device: 2.0s).
./extensions/SadTalkerm1/checkpoints/auido2pose_00140-model.pth
./extensions/SadTalkerm1/checkpoints/shape_predictor_68_face_landmarks.dat
./extensions/SadTalkerm1/checkpoints/facevid2vid_00189-model.pth.tar
/var/folders/6d/69zsy_g132gcld2sxqz7ks6w0000gn/T/gradio/4b4ef30ff7fadbc27f3d443e73adccb08df1d27e/tmpjguvsh4p.png
landmark Det:: 100%|██████████████████████████████| 1/1 [00:03<00:00,  3.09s/it]
3DMM Extraction In Video:: 100%|██████████████████| 1/1 [00:00<00:00,  5.03it/s]
mel:: 100%|███████████████████████████████| 762/762 [00:00<00:00, 130191.03it/s]
audio2exp:: 100%|██████████████████████████████| 77/77 [00:00<00:00, 143.02it/s]
Traceback (most recent call last):
  File "/Users/richard/miniconda3/lib/python3.10/site-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/richard/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/Users/richard/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/richard/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/Users/richard/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/Users/richard/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/richard/stable-diffusion-webui/modules/call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "/Users/richard/stable-diffusion-webui/extensions/SadTalkerM1/src/gradio_demo.py", line 124, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess)
  File "/Users/richard/stable-diffusion-webui/extensions/SadTalkerM1/src/facerender/animate.py", line 149, in generate
    predictions_video = make_animation(source_image, source_semantics, target_semantics,
  File "/Users/richard/stable-diffusion-webui/extensions/SadTalkerM1/src/facerender/modules/make_animation.py", line 109, in make_animation
    kp_canonical = kp_detector(source_image)
  File "/Users/richard/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/richard/stable-diffusion-webui/extensions/SadTalkerM1/src/facerender/modules/keypoint_detector.py", line 60, in forward
    feature_map = self.predictor(x)
  File "/Users/richard/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/richard/stable-diffusion-webui/extensions/SadTalkerM1/src/facerender/modules/util.py", line 365, in forward
    out = self.up_blocks(out)
  File "/Users/richard/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/richard/miniconda3/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/Users/richard/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/richard/stable-diffusion-webui/extensions/SadTalkerM1/src/facerender/modules/util.py", line 189, in forward
    out = self.conv(out)
  File "/Users/richard/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/richard/miniconda3/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 613, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/Users/richard/miniconda3/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 608, in _conv_forward
    return F.conv3d(
RuntimeError: Conv3D is not supported on MPS




How to solve it?

**Comment by johnnv1** [comment]
> How to solve it?
hey @crazyfish2020 this seems unrelated to Kornia project, I recommend opening an issue or asking in the right community/project
