### ISSUE TITLE
Segmentation Fault in run_5point

### ISSUE THREAD

**Issue by crockwell** [kornia/kornia#2642]
### Describe the bug

When calling kornia.geometry.epipolar.essential.run_5point I get a segmentation fault, running into the following error:

`Intel MKL ERROR: Parameter 3 was incorrect on entry to SGEBAL.
Segmentation fault (core dumped)`

The error appears to come from the following line:

`roots = torch.real(torch.linalg.eigvals(C))`

As it seems sometimes C contains inf values. I found skipping instances when C was inf fixed the error.

### Reproduction steps

```bash
1. call find_essential on a set of normalized correspondences OR
2. call run_5point
```

### Expected behavior

run_5point to execute without error.

### Environment

```shell
PyTorch version: 1.12.1                                                                                                [53/1867]Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Clang version: Could not collect
CMake version: version 3.27.6
Libc version: glibc-2.17

Python version: 3.9.18 (main, Sep 11 2023, 13:41:44)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-3.10.0-1062.12.1.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 10.0.130
CUDA_MODULE_LOADING set to:
GPU models and configuration:
GPU 0: NVIDIA GeForce GTX 1080 Ti
GPU 1: NVIDIA GeForce GTX 1080 Ti
GPU 2: NVIDIA GeForce GTX 1080 Ti
GPU 3: NVIDIA GeForce GTX 1080 Ti
GPU 4: NVIDIA GeForce GTX 1080 Ti
GPU 5: NVIDIA GeForce GTX 1080 Ti
GPU 6: NVIDIA GeForce GTX 1080 Ti
GPU 7: NVIDIA GeForce GTX 1080 Ti
GPU 8: NVIDIA GeForce GTX 1080 Ti

Nvidia driver version: 535.54.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:                                                                                                                   [20/1867]Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                40
On-line CPU(s) list:   0-39
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
Stepping:              1
CPU MHz:               1200.305
CPU max MHz:           3100.0000
CPU min MHz:           1200.0000
BogoMIPS:              4400.15
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-9,20-29
NUMA node1 CPU(s):     10-19,30-39
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_ppin intel_pt
tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts

Versions of relevant libraries:
[pip3] numpy==1.26.0
[pip3] numpy-quaternion==2022.4.3
[pip3] torch==1.12.1
[pip3] torchaudio==0.12.1
[pip3] torchvision==0.13.1
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46343
[conda] mkl-service               2.4.0            py39h5eee18b_1
[conda] mkl_fft                   1.3.8            py39h5eee18b_0
[conda] mkl_random                1.2.4            py39hdb19cb5_0
[conda] numpy                     1.26.0           py39h5f9d8c6_0
[conda] numpy-base                1.26.0           py39hb5e798b_0
[conda] numpy-quaternion          2022.4.3                 pypi_0    pypi
[conda] pytorch                   1.12.1          py3.9_cuda10.2_cudnn7.6.5_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.12.1               py39_cu102    pytorch
[conda] torchvision               0.13.1               py39_cu102    pytorch
[conda] triton                    2.0.0                    pypi_0    pypi
```

**Comment by edgarriba** [comment]
@crockwell are you open to contribute with the fix ? FYI, @weitong8591

**Comment by crockwell** [comment]
@edgarriba I dug into it and:
- kornia.geometry.solvers.determinant_to_polynomial occasionally returns 0 as it's last value, which causes cs[:,-1] to be 0, leading to inf C, leading to the seg fault.
- weirdly, once I copy the code for determinant_to_polynomial locally, it no longer seg faults. I'm not sure what would cause this as I'm using kornia 0.7.1-dev, which is the most recent version (and also the only version with run_5point), so the code should be the same on the website as is installed. Any ideas on what could be going on?

**Comment by edgarriba** [comment]
@crockwell i'm seeing that you have an "old" pytorch version (1.12.1) -- have you tried with updating 2.x ? the pytorch team sometimes update behaviours around the linear algebra package from big version to version.

**Comment by crockwell** [comment]
I just reran this with pytorch 2.1, unfortunately I still get a segmentation fault.

I do notice sometimes I alternatively get the following error:
`Traceback (most recent call last):
  File "clean_cv2_ransac_cv2_fineessential.py", line 334, in <module>
    main()
  File "clean_cv2_ransac_cv2_fineessential.py", line 218, in main
    E = find_essential(kpts0_norm.unsqueeze(0), kpts1_norm.unsqueeze(0)).cpu()
  File "/home/cnris/anaconda3/envs/kornia_0.7.0/lib/python3.9/site-packages/kornia/geometry/epipolar/essential.py", line 493, in find_essential
    E = run_5point(points1, points2, weights).to(points1.dtype)
  File "/home/cnris/anaconda3/envs/kornia_0.7.0/lib/python3.9/site-packages/kornia/geometry/epipolar/essential.py", line 202, in run_5point
    return torch.cat(E_models).view(-1, 3, 3).transpose(-1, -2)
RuntimeError: torch.cat(): expected a non-empty list of Tensors`

**Comment by weitong8591** [comment]
Hi! There used to be a nan filter here, hope it will help.
```
# check if the companion matrix contains nans or infs
if torch.isnan(C).any() or torch.isinf(C).any():
	continue
else:
	roots = torch.real(torch.linalg.eigvals(C))
```
Feel free to let me know if it works, then we can fix it in PR. Thanks!

**Comment by crockwell** [comment]
Yeah, this is basically the exact fix I used to make it work!

**Comment by edgarriba** [comment]
If anyone is interested in this, feel free to re-open the ticket. Thanks!
