### ISSUE TITLE
[DOCS] *args for FocalLoss should be **kwargs

### ISSUE THREAD

**Issue by Vimos** [kornia/kornia#363]
https://github.com/kornia/kornia/blob/1f540b4c74dfb00d012b89c9376a5f9ff957a0fb/kornia/losses/focal.py#L96

Otherwise, one can get 
```
Traceback (most recent call last):
  File "run_transformers.py", line 77, in <module>
    over_loss_fct = kornia.losses.FocalLoss(*args)
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/site-packages/kornia/losses/focal.py", line 56, in __init__
    self.gamma: torch.Tensor = torch.tensor(gamma)
TypeError: new(): invalid data type 'str'
```

**Comment by edgarriba** [comment]
@Vimos thanks! Could you open a PR fixing it ?
